"use client";
import {useEffect,useMemo,useRef,useState} from "react";

type Screen="home"|"create"|"vote"|"shop";
type Category="ALL"|"OUTER"|"TOP"|"BOTTOM"|"DRESS"|"SHOES"|"BAG"|"ACC";
type Item={id:string;category:Exclude<Category,"ALL">;brand:string;name:string;price:number;likes:string;image:string};
type Position={x:number;y:number;rotation:number};

const ITEMS:Item[]=[
 {id:"cardigan",category:"OUTER",brand:"MORNING DEW",name:"Muted Lilac Cardigan",price:49000,likes:"2.1K",image:"/catalog/street-21.jpg"},{id:"jacket",category:"OUTER",brand:"RECTO",name:"Linen Crop Jacket",price:129000,likes:"1.4K",image:"/catalog/street-25.jpg"},{id:"windbreaker",category:"OUTER",brand:"STILL ACTIVE",name:"Light Nylon Windbreaker",price:89000,likes:"3.8K",image:"/catalog/street-24.jpg"},
 {id:"top",category:"TOP",brand:"SÉRIE STUDIO",name:"Ivory Layered Top",price:49000,likes:"1.9K",image:"/catalog/women-01.jpg"},{id:"henley",category:"TOP",brand:"FORM STANDARD",name:"Soft Rib Henley Tee",price:42000,likes:"2.6K",image:"/catalog/street-01.jpg"},{id:"shirt",category:"TOP",brand:"ATELIER NINE",name:"Sheer Pocket Shirt",price:72000,likes:"1.7K",image:"/catalog/women-10.jpg"},
 {id:"denim",category:"BOTTOM",brand:"BLUE HOUR",name:"Indigo Bootcut Denim",price:69000,likes:"4.2K",image:"/catalog/street-16.jpg"},{id:"skirt",category:"BOTTOM",brand:"MOMENT EDITION",name:"Soft Pleats Skirt",price:89000,likes:"3.1K",image:"/catalog/women-12.jpg"},{id:"cargo",category:"BOTTOM",brand:"UTILITY CLUB",name:"Wide Pocket Cargo",price:79000,likes:"2.8K",image:"/catalog/street-13.jpg"},
 {id:"dress",category:"DRESS",brand:"ARCHIVE 101",name:"Bias Slip Dress",price:139000,likes:"5.4K",image:"/catalog/women-16.jpg"},{id:"mini-dress",category:"DRESS",brand:"MELLOW ROOM",name:"Square Neck Mini Dress",price:89000,likes:"2.2K",image:"/catalog/women-17.jpg"},{id:"sneakers",category:"SHOES",brand:"GROUND STANDARD",name:"Cream Platform Sneakers",price:64000,likes:"6.1K",image:"/catalog/accessory-01.jpg"},{id:"loafer",category:"SHOES",brand:"OFFICE HOURS",name:"Classic Penny Loafer",price:98000,likes:"1.8K",image:"/catalog/accessory-03.jpg"},
 {id:"bag",category:"BAG",brand:"MARGE SHERWOOD",name:"Soft Baguette Bag",price:89000,likes:"4.7K",image:"/catalog/accessory-09.jpg"},{id:"mini-bag",category:"BAG",brand:"FORME",name:"Mint Mini Boston Bag",price:59000,likes:"1.3K",image:"/catalog/accessory-10.jpg"},{id:"necklace",category:"ACC",brand:"NUMBERING",name:"Curve Chain Necklace",price:39000,likes:"2.5K",image:"/catalog/accessory-15.jpg"}
];
const CATEGORIES:Category[]=["ALL","TOP","BOTTOM","OUTER","DRESS","SHOES","BAG","ACC"];
const VOTES=[{a:["henley","denim","sneakers"],b:["top","cargo","sneakers"],an:"SOFT MINIMAL",bn:"CITY LAYERED"},{a:["top","cargo","sneakers"],b:["henley","skirt","sneakers"],an:"CLEAN UTILITY",bn:"QUIET PREP"},{a:["cardigan","denim","sneakers"],b:["henley","denim","loafer"],an:"SOFT COLOR",bn:"DARK CLASSIC"}];
const AUTO:Record<string,Position>={OUTER:{x:27,y:32,rotation:-4},TOP:{x:57,y:28,rotation:3},BOTTOM:{x:59,y:61,rotation:-2},DRESS:{x:50,y:53,rotation:1},SHOES:{x:31,y:81,rotation:4},BAG:{x:80,y:58,rotation:-5},ACC:{x:79,y:24,rotation:6}};
const won=(n:number)=>`₩${n.toLocaleString("ko-KR")}`;
const byIds=(ids:string[])=>ITEMS.filter(i=>ids.includes(i.id));
const sum=(list:Item[])=>list.reduce((n,i)=>n+i.price,0);

function FlatLay({items,interactive=false,positions={},onPosition}:{items:Item[];interactive?:boolean;positions?:Record<string,Position>;onPosition?:(id:string,p:Position)=>void}){
 const board=useRef<HTMLDivElement>(null);const drag=useRef<{id:string;sx:number;sy:number;p:Position}|null>(null);
 const down=(e:React.PointerEvent<HTMLElement>,item:Item)=>{if(!interactive)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={id:item.id,sx:e.clientX,sy:e.clientY,p:positions[item.id]??AUTO[item.category]}};
 const move=(e:React.PointerEvent<HTMLElement>)=>{if(!drag.current||!board.current||!onPosition)return;const b=board.current.getBoundingClientRect(),d=drag.current;onPosition(d.id,{...d.p,x:Math.max(10,Math.min(90,d.p.x+(e.clientX-d.sx)/b.width*100)),y:Math.max(14,Math.min(89,d.p.y+(e.clientY-d.sy)/b.height*100))})};
 return <div className="flat-board" ref={board}><div className="board-meta"><b>MUSE / OUTFIT CANVAS</b><span>{interactive?"DRAG TO ARRANGE":"COMMUNITY LOOK"}</span></div>{items.map(item=>{const p=positions[item.id]??AUTO[item.category];return <article key={item.id} className={`flat-item flat-${item.category.toLowerCase()}`} style={{left:`${p.x}%`,top:`${p.y}%`,"--rotation":`${p.rotation}deg`} as React.CSSProperties} onPointerDown={e=>down(e,item)} onPointerMove={move} onPointerUp={()=>drag.current=null}><span>{item.category}</span><img src={item.image} alt={`${item.brand} ${item.name}`} draggable={false}/></article>})}</div>
}
function Check({ok,children}:{ok:boolean;children:React.ReactNode}){return <p className={`check ${ok?"ok":""}`}><b>{ok?"✓":"○"}</b>{children}</p>}
function SelectedList({items}:{items:Item[]}){return <div className="selected-list">{items.map(item=><div key={item.id}><img src={item.image} alt=""/><span><small>{item.category}</small>{item.name}</span><b>{won(item.price)}</b></div>)}</div>}

export default function MusePlay(){
 const[screen,setScreen]=useState<Screen>("home"),[category,setCategory]=useState<Category>("ALL"),[selectedIds,setSelectedIds]=useState(["henley","denim","sneakers"]),[history,setHistory]=useState<string[][]>([]),[positions,setPositions]=useState<Record<string,Position>>({}),[challenge,setChallenge]=useState(false),[seconds,setSeconds]=useState(180),[completed,setCompleted]=useState(false),[voteRound,setVoteRound]=useState(0),[cheaper,setCheaper]=useState(false),[toast,setToast]=useState("");
 const selected=useMemo(()=>byIds(selectedIds),[selectedIds]),visible=category==="ALL"?ITEMS:ITEMS.filter(i=>i.category===category),total=sum(selected),cats=new Set(selected.map(i=>i.category));
 const budget=total>0&&total<=200000,required=cats.has("SHOES")&&((cats.has("TOP")&&cats.has("BOTTOM"))||cats.has("DRESS")),count=selected.length>=3,ready=budget&&required&&count;
 useEffect(()=>{if(!challenge||screen!=="create"||completed||seconds<=0)return;const id=setInterval(()=>setSeconds(v=>Math.max(0,v-1)),1000);return()=>clearInterval(id)},[challenge,screen,completed,seconds]);
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),1900)},go=(s:Screen)=>{setScreen(s);scrollTo({top:0,behavior:"smooth"})},start=()=>{setSeconds(180);setChallenge(true);setCompleted(false);go("create")};
 const toggle=(item:Item)=>{setHistory(h=>[...h.slice(-19),selectedIds]);if(selectedIds.includes(item.id)){setSelectedIds(a=>a.filter(id=>id!==item.id));return}const conflicts=item.category==="DRESS"?["DRESS","TOP","BOTTOM"]:["TOP","BOTTOM"].includes(item.category)?[item.category,"DRESS"]:[item.category],base=item.category==="ACC"?selectedIds:selectedIds.filter(id=>!conflicts.includes(ITEMS.find(i=>i.id===id)?.category??"ACC"));setSelectedIds([...base,item.id])};
 const time=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
 const Header=<header className="site-header"><button className="wordmark" onClick={()=>go("home")}><b>MUSE PLAY</b><span>PLAY COMMERCE · PUBLIC BETA</span></button><nav>{(["home","create","vote","shop"]as Screen[]).map(s=><button key={s} className={screen===s?"active":""} onClick={()=>{if(s==="create")setCompleted(false);go(s)}}>{s==="home"?"PLAY HOME":s==="shop"?"SHOP THE LOOK":s.toUpperCase()}</button>)}</nav><p>CREATE · VOTE · SHOP<br/><span>REAL PRODUCT DATA</span></p></header>;
 return <main>{Header}
 {screen==="home"&&<div className="page home"><section className="hero"><small>WHAT WOULD YOU WEAR?</small><h1>STYLE THE<br/>MOMENT.</h1><p>Turn real products into a playable fashion edit.<br/>Create the look, enter the battle, shop what wins.</p><div>CREATE　→　VOTE　→　DISCOVER　→　SHOP</div><button className="primary yellow" onClick={start}>START CHALLENGE →</button></section><section className="mission"><div><small>MIYU&apos;S MISSION · BUDGET ≤ ₩200K</small><h2>FRIDAY DATE<br/>IN SEONGSU</h2><blockquote>“오늘 저녁 갑자기 소개팅이 생겼어.<br/>20만원 안으로 코디해줄래?”</blockquote><p><span>29°C</span><span>3 MIN</span><span>TOP + BOTTOM + SHOES</span></p><button className="primary" onClick={start}>HELP MIYU →</button></div><figure><div><img src="/miyu-doll-atlas-v2.png" alt="Mission guide MIYU"/></div><b>MISSION GUIDE · MIYU</b></figure></section><section className="modules">{[["01","CREATE LOOK","Play with real products on a flat lay canvas."],["02","VOTE NOW","Vote for the style, not the person."],["03","SHOP THE LOOK","Move from community inspiration to cart."],["04","BEAUTY PLAY","A separate play type · coming soon."]].map((x,i)=><button key={x[0]} onClick={()=>i===0?go("create"):i===1?go("vote"):i===2?go("shop"):notify("BEAUTY PLAY is coming next.")}><small>{x[0]}</small><b>{x[1]}</b><span>{x[2]}</span><i>→</i></button>)}</section></div>}
 {screen==="create"&&!completed&&<div className="page"><Heading kicker="CREATE LOOK" title="BUILD THE FRIDAY SEONGSU EDIT." copy="Real products become game items · drag them into your editorial layout."/><div className="categories">{CATEGORIES.map(c=><button className={c===category?"active":""} key={c} onClick={()=>setCategory(c)}>{c} <small>{c==="ALL"?ITEMS.length:ITEMS.filter(i=>i.category===c).length}</small></button>)}</div><div className="create-layout"><section className="products"><Title left="DISCOVER PRODUCTS" right={`${visible.length} PRODUCTS`}/><div className="product-grid">{visible.map(item=><article className={selectedIds.includes(item.id)?"selected":""} key={item.id}><img src={item.image} alt={`${item.brand} ${item.name}`}/><small>{item.brand}</small><h3>{item.name}</h3><div><b>{won(item.price)}</b><span>♡ {item.likes}</span></div><button onClick={()=>toggle(item)}>{selectedIds.includes(item.id)?"REMOVE":"ADD +"}</button></article>)}</div></section><section className="canvas-panel"><Title left="OUTFIT CANVAS · FLAT LAY" right={challenge?`${time} LEFT`:"FREE PLAY · NO TIMER"}/><FlatLay items={selected} interactive positions={positions} onPosition={(id,p)=>setPositions(v=>({...v,[id]:p}))}/><p className="canvas-help">AUTO-ARRANGED BY CATEGORY · DRAG ANY PRODUCT TO FINE-TUNE</p></section><aside className="challenge"><small>TODAY&apos;S MISSION</small><h2>FRIDAY · SEONGSU<br/>FIRST DATE</h2><p>SEOUL · 7PM · 29°C<br/>BUDGET ≤ ₩200,000</p><div className="edit-actions"><button disabled={!history.length} onClick={()=>{const p=history.at(-1);if(p){setSelectedIds(p);setHistory(h=>h.slice(0,-1))}}}>UNDO</button><button onClick={()=>{setHistory(h=>[...h,selectedIds]);setSelectedIds([])}}>RESET</button></div><h3>CHALLENGE CHECK</h3><Check ok={budget}>Budget under ₩200,000</Check><Check ok={required}>TOP + BOTTOM + SHOES</Check><Check ok={count}>{selected.length} items selected</Check><SelectedList items={selected}/><footer><span>{selected.length} ITEMS</span><b>{won(total)}</b></footer><p className={ready?"ready":""}>{ready?"READY TO ENTER":"COMPLETE THE CONDITIONS"}</p><button className="primary" disabled={!ready} onClick={()=>{setChallenge(false);setCompleted(true)}}>SUBMIT LOOK →</button></aside></div></div>}
 {screen==="create"&&completed&&<div className="page"><Heading kicker="LOOK COMPLETE" title="MIYU ♥ YOUR LOOK" copy="A community-ready card made from the same real product data."/><div className="result"><section><small>LOOK #1842 · COMMUNITY EDIT</small><FlatLay items={selected}/><p>CREATE WITH PRODUCTS. VOTE FOR THE STYLE.</p></section><aside><small>FRIDAY SEONGSU DATE</small><h2>LOOK #1842</h2><h3>{selected.length} ITEMS<br/>TOTAL {won(total)}<br/>by USER</h3><SelectedList items={selected}/><div><button onClick={()=>notify("LOOK #1842 saved.")}>SAVE LOOK</button><button className="primary" onClick={()=>go("vote")}>ENTER BATTLE →</button><button onClick={()=>setCompleted(false)}>← EDIT LOOK</button></div></aside></div></div>}
 {screen==="vote"&&<Vote round={voteRound} setRound={setVoteRound} goShop={()=>go("shop")}/>} 
 {screen==="shop"&&<Shop cheaper={cheaper} setCheaper={setCheaper} notify={notify}/>} {toast&&<div className="toast">{toast}</div>}</main>
}

function Heading({kicker,title,copy}:{kicker:string;title:string;copy:string}){return <div className="heading"><div><small>{kicker}</small><h1>{title}</h1></div><p>{copy}</p></div>}
function Title({left,right}:{left:string;right:string}){return <div className="panel-title"><b>{left}</b><strong>{right}</strong></div>}
function Vote({round,setRound,goShop}:{round:number;setRound:(n:number)=>void;goShop:()=>void}){if(round>=5)return <div className="page"><Heading kicker="5 VOTES COMPLETE" title="YOUR TASTE" copy="Fast choices become a useful discovery signal."/><div className="taste"><section><small>YOUR TASTE</small><h2>QUIET<br/>CONTRAST</h2><p>Community decides what looks good — not an arbitrary score.</p></section><aside>{[["MINIMAL",76],["CASUAL",68],["STREET",54]].map(([x,n])=><div key={x}><b>{x}</b><i><em style={{width:`${n}%`}}/></i><span>{n}%</span></div>)}<button className="primary" onClick={goShop}>DISCOVER LOOKS FOR YOU →</button><button onClick={()=>setRound(0)}>VOTE AGAIN</button></aside></div></div>;
 const set=VOTES[round%3];return <div className="page"><Heading kicker={`VOTE ${round+1} / 5`} title="WHICH WOULD YOU WEAR?" copy="FRIDAY SEONGSU DATE · Vote for the style, not the person."/><div className="progress"><i style={{width:`${round*20}%`}}/></div><div className="vote"><b>VS</b>{(["A","B"]as const).map(c=>{const list=byIds(c==="A"?set.a:set.b);return <article key={c}><header><span>LOOK {c}</span><b>{won(sum(list))}</b></header><FlatLay items={list}/><h2>{c==="A"?set.an:set.bn}</h2><p>Same mission · same canvas · real products</p><button onClick={()=>setRound(round+1)}>CHOOSE {c}</button></article>})}</div></div>}
function Shop({cheaper,setCheaper,notify}:{cheaper:boolean;setCheaper:(v:boolean)=>void;notify:(s:string)=>void}){const list=byIds(["cardigan","top","denim","sneakers","bag"]);return <div className="page"><Heading kicker="SHOP THE WINNING LOOK" title="FROM COMMUNITY PICK TO CART." copy="The exact products behind the look — individually selectable or all at once."/><div className="shop"><section><small>WEEKLY WINNER · 12.8K SAVES</small><FlatLay items={list}/><h2>FRIDAY SEONGSU DATE</h2><p>SHOP THE PRODUCTS, NOT A GENERATED OUTFIT</p></section><aside><small>SHOPPABLE EDIT</small><h2>THE LOOK, ITEM BY ITEM</h2><h3>LOVE THE LOOK, NOT THE PRICE?</h3><div className="switch"><button className={!cheaper?"active":""} onClick={()=>setCheaper(false)}>ORIGINAL · ₩320K</button><button className={cheaper?"active":""} onClick={()=>setCheaper(true)}>SIMILAR · ₩185K</button></div><div className="shop-list">{list.map(i=><div key={i.id}><img src={i.image} alt=""/><span><small>{i.brand}</small><b>{i.name}</b></span><strong>{won(Math.round(i.price*(cheaper?.58:1)))}</strong><button onClick={()=>notify(`${i.name} added.`)}>ADD</button></div>)}</div><footer><span>TOTAL</span><b>{cheaper?"₩185,600":"₩320,000"}</b></footer><button className="primary" onClick={()=>notify("Complete look added to your bag.")}>ADD ALL TO BAG</button><button onClick={()=>setCheaper(!cheaper)}>{cheaper?"VIEW ORIGINAL LOOK":"FIND ALTERNATIVES →"}</button></aside></div></div>}
